development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: xchange_dev
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: xchange_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: xchange_prod
  pool: 5
  username: root
  password:
  host: localhost
